name: custom_call_fake_api_challenge
description: "A Flutter package that allows consuming the Fake Store API to fetch data, provides services to fetch lists of products, categories and users with error handling."
version: 1.0.1
homepage: "https://github.com/jlmd1992/custom_call_fake_api_challenge_pkg"

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
